### ISSUE TITLE
Found a problem with the Desktop

### ISSUE THREAD

**Issue by partizan4ez** [YurinDoctrine/adbloat#4]
Hello!

I have encountered a problem on my Mi 11 Ultra phone: after using a certain script, the phone works fine, but the "com.miui.home" launcher starts using too much RAM.

I tried resetting the app settings and rolling back the update, but it didn't help. Unfortunately, the problem remains.
![ADBAppControl_EahYdy9E3G](https://github.com/user-attachments/assets/c081bf11-8c47-41ac-b888-eba77cdd86d4)

**Comment by YurinDoctrine** [comment]
How much ram does it take usually before you ran the script?

**Comment by partizan4ez** [comment]
The problem only occurred with the desktop: it started consuming a lot of RAM. In addition, it takes longer to load when exiting applications. Previously, I always had 7 out of 12 gigabytes of free RAM, but now there is only 4-5 gigabytes left.

**Comment by partizan4ez** [comment]
Friend, I found the reason for this desktop behavior. In the developer settings, I disabled the Do not store Activiti option.

**Comment by partizan4ez** [comment]
always_finish_activities

**Comment by YurinDoctrine** [comment]
Thanks for the feedback. :+1:
